### ISSUE TITLE
Version list

### ISSUE THREAD

**Issue by Flukethoughts** [ThePotato97/PotatoLoader#1]
![image](https://user-images.githubusercontent.com/9858437/98032846-39849b80-1dda-11eb-955d-7fad10d54a8e.png)

**Comment by ThePotato97** [comment]
why are you not just using https://github.com/HerpDerpinstine/MelonLoader

**Comment by Flukethoughts** [comment]
Removal of 2019.4.7.zip from github

**Comment by ThePotato97** [comment]
why did he even do that anyway

**Comment by Flukethoughts** [comment]
To be honest not sure I have got the file but can't do much with it also my discord is fluke#0470

**Comment by ThePotato97** [comment]
should work now

**Comment by ThePotato97** [comment]
https://github.com/ThePotato97/PotatoLoader/releases/download/v0.2.7.2/MelonLoader.Installer.exe

**Comment by Bluscream** [comment]
We did this because some pricks decided to abuse ML for their fun ruining the game for everyone else

**Comment by ThePotato97** [comment]
> 
> 
> We did this because some pricks decided to abuse ML for their fun ruining the game for everyone else

People who are ruining public lobbies with toxic behavior deserve to be game banned, messing around in a private lobby with friends is the only use case I support people using mods.

**Comment by Bluscream** [comment]
Sadly there's no way to differentiate between these two groups when they are asking questions about suspicious things.
Also someone might create a hack for himself and their few friends but then it's being shared around and used by others like @Flukethoughts to do bad stuff in public.
Especially with Phasmophobia (which is why the 2019.4.7 artifacts where removed) it's basically impossible to find a legitimate public lobby these days.

**Comment by Flukethoughts** [comment]
@Bluscream I don't do bad stuff I used this with my family be nice

**Comment by Flukethoughts** [comment]
Seems blue banned me from discord even though I didn't do anything wrong thanks mate
